# Generated by Django 4.2.23 on 2025-06-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_school_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbudget',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_budgets', to='budget.budgetperiod'),
        ),
        migrations.AddField(
            model_name='schoolbudget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_school_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbudget',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.school'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='budget_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='budget.budgetlineitem'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='destination_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='budget.budgetlineitem'),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='source_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='budget.budgetlineitem'),
        ),
        migrations.AddField(
            model_name='budgetreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_budget_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetreport',
            name='school_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='budget.schoolbudget'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='budget_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budget_line_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='related_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_line_items', to='grants.grantproposal'),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='school_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.schoolbudget'),
        ),
    ]
