# Generated by Django 4.2.23 on 2025-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
