# Generated by Django 4.2.23 on 2025-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reb_officer', 'REB Officer'), ('school_admin', 'School Administrator'), ('teacher', 'Teacher'), ('community_member', 'Community Member'), ('system_admin', 'System Administrator'), ('supplier', 'Supplier')], default='teacher', max_length=20),
        ),
    ]
