# Generated by Django 4.2.23 on 2025-07-01 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('review', 'Review')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'proposal_title')},
            },
        ),
    ]
