# Generated by Django 4.2.23 on 2025-07-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        ('ai_engine', '0004_aimodelstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction', to='grants.grantproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(default='score', max_length=50)),
                ('score', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_anomalies', to='grants.grantproposal')),
            ],
        ),
    ]
