# Generated by Django 4.2.23 on 2025-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Extracted text from OCR analysis.', null=True),
        ),
    ]
