# Generated by Django 4.2.23 on 2025-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_add_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantproposal',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total project cost', max_digits=12),
        ),
        migrations.AlterField(
            model_name='grantproposal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current allocated budget amount', max_digits=12),
        ),
    ]
