# Generated by Django 4.2.23 on 2025-08-13 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0004_grantproposal_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGrantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fiscal_year', models.PositiveIntegerField(help_text='Fiscal year (e.g., 2024)', unique=True)),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total grant budget for the year', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already allocated to proposals', max_digits=15)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already disbursed', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allocation is currently active')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this allocation', null=True)),
                ('allocation_notes', models.TextField(blank=True, help_text='Internal notes for administrators', null=True)),
                ('start_date', models.DateField(help_text='Start date of the fiscal year')),
                ('end_date', models.DateField(help_text='End date of the fiscal year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_grant_allocations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grant_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Total Grant Allocation',
                'verbose_name_plural': 'Total Grant Allocations',
                'db_table': 'grants_total_grant_allocation',
                'ordering': ['-fiscal_year'],
            },
        ),
    ]
