# Generated by Django 4.2.23 on 2025-08-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0005_totalgrantallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantproposal',
            name='change_request_comments',
            field=models.TextField(blank=True, help_text='Comments from admin requesting changes', null=True),
        ),
        migrations.AddField(
            model_name='grantproposal',
            name='change_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantproposal',
            name='change_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grantproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
