# Generated by Django 4.2.23 on 2025-07-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0002_proposaldocument_ocr_text'),
        ('reporting', '0003_proposalcriterion_suppliercriterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCriterionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='supplier_criteria/')),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.suppliercriterion')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_criterion_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_supplier_criterion_response',
                'unique_together': {('supplier', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='ProposalCriterionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='proposal_criteria/')),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.proposalcriterion')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_responses', to='grants.grantproposal')),
            ],
            options={
                'db_table': 'reporting_proposal_criterion_response',
                'unique_together': {('proposal', 'criterion')},
            },
        ),
    ]
