# Generated by Django 4.2.23 on 2025-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='guide_document',
            field=models.FileField(blank=True, help_text='Upload a PDF or DOCX guide', null=True, upload_to='training_guides/'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link for training video', null=True),
        ),
    ]
